/** Profissões da saúde (cadastro público) */
export const PROFISSOES_SAUDE = [
  'Médico',
  'Enfermeiro',
  'Fonoaudiólogo',
  'Nutricionista',
  'Terapeuta Ocupacional',
  'Psicólogo',
  'Educador Físico',
  'Musicoterapeuta',
  'Fisioterapeuta',
  'Biomédico',
  'Outro',
] as const;

/** Especialidades médicas (multi-select). Clínica Médica = formação base. */
export const ESPECIALIDADES_MEDICAS = [
  'Clínica Médica',
  'Anestesiologia',
  'Angiologia',
  'Cardiologia',
  'Cirurgia Geral',
  'Cirurgia Cardiovascular',
  'Cirurgia de Cabeça e Pescoço',
  'Cirurgia do Aparelho Digestivo',
  'Cirurgia Pediátrica',
  'Cirurgia Plástica',
  'Cirurgia Torácica',
  'Cirurgia Vascular',
  'Dermatologia',
  'Endocrinologia e Metabologia',
  'Gastroenterologia',
  'Genética Médica',
  'Geriatria',
  'Ginecologia e Obstetrícia',
  'Hematologia e Hemoterapia',
  'Homeopatia',
  'Infectologia',
  'Mastologia',
  'Medicina de Família e Comunidade',
  'Medicina do Trabalho',
  'Medicina de Tráfego',
  'Medicina Esportiva',
  'Medicina Física e Reabilitação',
  'Medicina Intensiva',
  'Medicina Legal e Perícia Médica',
  'Medicina Nuclear',
  'Medicina Preventiva e Social',
  'Nefrologia',
  'Neurocirurgia',
  'Neurologia',
  'Nutrologia',
  'Oftalmologia',
  'Oncologia Clínica',
  'Ortopedia e Traumatologia',
  'Otorrinolaringologia',
  'Patologia',
  'Patologia Clínica',
  'Pediatria',
  'Pneumologia',
  'Psiquiatria',
  'Radiologia e Diagnóstico por Imagem',
  'Radioterapia',
  'Reumatologia',
  'Urologia',
] as const;
