export type EmailContato = {
  nome: string;
  email: string;
};

/** Contatos médicos para envio pelo Painel de E-mail (apenas e-mails validados). */
export const EMAIL_CONTATOS: EmailContato[] = [
  { nome: 'Adalgisa Maria Santos Leite', email: 'dra.adalgisaleite@gmail.com' },
  { nome: 'Alana Mendes de Sousa', email: 'alanamsousa@hotmail.com' },
  { nome: 'Alvaro Landim Cruz Santana', email: 'alvarolandim1@hotmail.com' },
  { nome: 'Amanda Borges de Melo Vieira', email: 'amandabv1@hotmail.com' },
  { nome: 'Amanda Cavalcante Colares', email: 'amandacolares.med@gmail.com' },
  { nome: 'Amanda Progenio dos Santos', email: 'draamandaprogenio@gmail.com' },
  { nome: 'Ariana Amorim de Paula', email: 'arianadepaula@outlook.com' },
  { nome: 'Beatriz Bezerra Saraiva', email: 'beatrizsaraiva1@outlook.com' },
  { nome: 'Beatriz Catunda de Almeida', email: 'beatrizcatundaalmeida@gmail.com' },
  { nome: 'Bianca Castro Martins de Oliveira Teofilo', email: 'biancacmoteofilo@gmail.com' },
  { nome: 'Caio Lucio Alencar de Andrade', email: 'caiolucio7@hotmail.com' },
  { nome: 'Carolina de Castro Alves Linhares Feijao', email: 'carolinamedunichristus@gmail.com' },
  { nome: 'Catarina Ester Gomes Menezes', email: 'catarina.gomes.menezes@gmail.com' },
  { nome: 'Clivia Lima Araujo', email: 'clivialimaaraujo@gmail.com' },
  { nome: 'Conrado Franco de Oliveira', email: 'conradofrancomd@gmail.com' },
  { nome: 'Eliana Mesquita Alves', email: 'elimesquita05@gmail.com' },
  { nome: 'Ernane Bruno Osório Neto', email: 'ernaneb@gmail.com' },
  { nome: 'Ernesto Lisuan Diaz Canizares', email: 'ernestocanizares688@gmail.com' },
  { nome: 'Everton Alencar Moura', email: 'evertonmour@hotmail.com' },
  { nome: 'Gabrielle de Sousa Vitor', email: 'gabrielle.s.vitor@hotmail.com' },
  { nome: 'Gardênia Teixeira Holanda', email: 'gardeniateixeiraholanda@gmail.com' },
  { nome: 'Glauter Carlos Félix', email: 'glauterfelix@gmail.com' },
  { nome: 'Helmer Antonio Pardo Jimenez', email: 'hellpar123@gmail.com' },
  { nome: 'Jessica Karolyne Feitosa Melo Meireles', email: 'jessicammeireles17@gmail.com' },
  { nome: 'Joao Nathanael Sales Rodrigues', email: 'joaonsrodrigues@gmail.com' },
  { nome: 'Lino Santos de Sousa', email: 'linosantosdesousa.medufc@gmail.com' },
  { nome: 'Luana Sobreira Viana Aguiar', email: 'luanasvianaag@gmail.com' },
  { nome: 'Lucas Yuri Ponte Viana', email: 'viana.yurip@gmail.com' },
  { nome: 'Ludijane Dayves Prado Passos Filho', email: 'ludijaneprado@gmail.com' },
  { nome: 'Luiza Helena Paula Pessoa Marques Pinheiro', email: 'luizahppmp@msn.com' },
  { nome: 'Madelaine Perez Corcho Arbolaez', email: 'mperezcorcho@gmail.com' },
  { nome: 'Marcelo de Moraes Andrade', email: 'mmandradeuece@hotmail.com' },
  { nome: 'Marcos Venicio Gurgel Fernandes', email: 'markimvenicio@yahoo.com.br' },
  { nome: 'Maria Yasmim de Oliveira Freitas', email: 'yasmimfreitas@gmail.com' },
  { nome: 'Marina Oliveira Severiano', email: 'marina.oseveriano@gmail.com' },
  { nome: 'Matheus Feitoza Gomes', email: 'matheusfeitoza@yahoo.com.br' },
  { nome: 'Maylsson Ramos de Souza', email: 'maylssonramosmed01@hotmail.com' },
  { nome: 'Miguel Felix de Moura Neto', email: 'miguelfelixmed@gmail.com' },
  { nome: 'Paula Burlamaqui Castello Branco Melo', email: 'paulaburlamaqui@hotmail.com' },
  { nome: 'Paulo Henrique Araùjo Parente', email: 'phparente@hotmail.com' },
  { nome: 'Pedro Henrique Messias da Rocha', email: 'pedrohenriquehmr29@gmail.com' },
  { nome: 'Priscila Silva Coelho', email: 'priscilacltda@gmail.com' },
  { nome: 'Rafael Bezerra de Almeida', email: 'rafael.praia@hotmail.com' },
  { nome: 'Rafael Lima da Cunha', email: 'rafaelcunha.rlc@gmail.com' },
  { nome: 'Rafhael Maia Santiago', email: 'rafhaelmaiasantiago@gmail.com' },
  { nome: 'Raquel Line Pinto de Menezes', email: 'raquel.line.pm@hotmail.com' },
  { nome: 'Renata Esteves Frota', email: 'restevesfrota@gmail.com' },
  { nome: 'Sara Raquel da Silva Pereira', email: 'sara_raquel@live.com' },
  { nome: 'Sayro Coelho Andrade de Sousa', email: 'sayrosousa@hotmail.com' },
  { nome: 'Sheywe Arnaldo Mendes', email: 'sheywearnaldo@hotmail.com' },
  { nome: 'Tereza Amália Gomes Marques de Sousa', email: 'gms.tereza@gmail.com' },
  { nome: 'Thiago Gomes Leal de Almeida', email: 'drthiagoleal@hotmail.com' },
  { nome: 'Thomaz Martins Magi', email: 'thomazmagi@hotmail.com' },
  { nome: 'Victor de Autran Nunes Matos', email: 'victorautran@hotmail.com' },
];
